sudo: required

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt install libboost-all-dev

language: cpp

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make