version: '{build}'

image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release
    - GENERATOR: "Visual Studio 15"
      CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds -DENABLE_TESTING=1
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - ctest -VV -C "%CONFIG%"